<?php
namespace App\Libraries\Facades;

use Illuminate\Support\Facades\Facade;

class RSA extends Facade
{
    protected static function getFacadeAccessor()
    {
        // parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return \App\Libraries\Openssl\RSA::class;
    }
}