<?php
namespace App\Libraries\Facades;
use Illuminate\Support\Facades\Facade;

class Snowflake extends Facade
{
    protected static function getFacadeAccessor()
    {
        // parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return \App\Libraries\Snowflake\Snowflake::class;
    }
}