<?php
/**
 * Created by LWL.
 * User: LUWENLONG
 * Date: 2019/3/14
 * Time: 21:26
 */

namespace App\Libraries\Facades;


use Illuminate\Support\Facades\Facade;

class Upload extends Facade
{
    protected static function getFacadeAccessor()
    {
        return \App\Libraries\Images\Upload::class;
    }

    public static function setFacadeApplication($app)
    {
        parent::setFacadeApplication($app); // TODO: Change the autogenerated stub
    }
}